[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  framework = "#custom"
  command = "npm run dev:vite"
  targetPort = 3000
  port = 8889